package  com.ingweb.prestamoequipos.model;



import java.util.Date;

/**
 * RequestLoanDevices generated by hbm2java
 */
public class RequestLoanDevices  implements java.io.Serializable {


     private int idrequestLoanDevices;
     private Devices devices;
     private Users usersByUserApproved;
     private Users usersByUserRequest;
     private Date dateLoan;
     private Date dateClose;
     private Date dateRequest;
     private Boolean approved;

    public RequestLoanDevices() {
    }

	
    public RequestLoanDevices(int idrequestLoanDevices, Devices devices, Users usersByUserRequest, Date dateLoan, Date dateClose, Date dateRequest) {
        this.idrequestLoanDevices = idrequestLoanDevices;
        this.devices = devices;
        this.usersByUserRequest = usersByUserRequest;
        this.dateLoan = dateLoan;
        this.dateClose = dateClose;
        this.dateRequest = dateRequest;
    }
    public RequestLoanDevices(int idrequestLoanDevices, Devices devices, Users usersByUserApproved, Users usersByUserRequest, Date dateLoan, Date dateClose, Date dateRequest, Boolean approved) {
       this.idrequestLoanDevices = idrequestLoanDevices;
       this.devices = devices;
       this.usersByUserApproved = usersByUserApproved;
       this.usersByUserRequest = usersByUserRequest;
       this.dateLoan = dateLoan;
       this.dateClose = dateClose;
       this.dateRequest = dateRequest;
       this.approved = approved;
    }
   
    public int getIdrequestLoanDevices() {
        return this.idrequestLoanDevices;
    }
    
    public void setIdrequestLoanDevices(int idrequestLoanDevices) {
        this.idrequestLoanDevices = idrequestLoanDevices;
    }
    public Devices getDevices() {
        return this.devices;
    }
    
    public void setDevices(Devices devices) {
        this.devices = devices;
    }
    public Users getUsersByUserApproved() {
        return this.usersByUserApproved;
    }
    
    public void setUsersByUserApproved(Users usersByUserApproved) {
        this.usersByUserApproved = usersByUserApproved;
    }
    public Users getUsersByUserRequest() {
        return this.usersByUserRequest;
    }
    
    public void setUsersByUserRequest(Users usersByUserRequest) {
        this.usersByUserRequest = usersByUserRequest;
    }
    public Date getDateLoan() {
        return this.dateLoan;
    }
    
    public void setDateLoan(Date dateLoan) {
        this.dateLoan = dateLoan;
    }
    public Date getDateClose() {
        return this.dateClose;
    }
    
    public void setDateClose(Date dateClose) {
        this.dateClose = dateClose;
    }
    public Date getDateRequest() {
        return this.dateRequest;
    }
    
    public void setDateRequest(Date dateRequest) {
        this.dateRequest = dateRequest;
    }
    public Boolean getApproved() {
        return this.approved;
    }
    
    public void setApproved(Boolean approved) {
        this.approved = approved;
    }




}


